"""CognitiveState — unified state object passed through the 12-stage cognitive pipeline."""

from __future__ import annotations

from typing import Any
from uuid import UUID, uuid4

from pydantic import BaseModel, Field

from theo_core.domain.runtime.entities.cognitive_workspace import CognitiveWorkspace
from theo_core.domain.runtime.entities.goal import Goal  # noqa: TC001
from theo_core.domain.runtime.entities.percept import Percept  # noqa: TC001
from theo_core.domain.runtime.entities.plan import Plan  # noqa: TC001


class CognitiveState(BaseModel):
    """Unified state object representing the full state of a single cognitive turn.

    Passed sequentially through all 12 stages of the CognitiveEngine.

    Attributes:
        cycle_id: Unique UUID identifier for this cognitive cycle iteration.
        raw_input: Raw text string received from the user.
        percept: Normalized Percept object created by Perception Engine.
        context: Ephemeral session context snapshot.
        memory_classification: Category assigned by Memory Classifier.
        retrieved_memories: List of retrieved MemoryEntry dictionaries or objects.
        retrieved_knowledge: Facts retrieved from Knowledge Graph.
        active_goal: Currently selected Goal.
        plan: Ordered Action sequence generated by Planner.
        inference_result: Candidates and decision parameters from Inference Engine.
        reflection_result: Satisfaction evaluation from Reflection Engine.
        decision: Decision dictionary from Decision Engine.
        response_text: Final output text string generated by Response Generator.
        workspace: CognitiveWorkspace intermediate workspace.
        stages_visited: Tuple of stage names visited during processing.
        learning_actions: Actions recorded for offline model tuning/tracing.

    """

    cycle_id: UUID = Field(default_factory=uuid4)
    raw_input: str = ""
    percept: Percept | None = None
    context: dict[str, Any] = Field(default_factory=dict)
    memory_classification: str = "working"
    retrieved_memories: list[dict[str, Any]] = Field(default_factory=list)
    retrieved_knowledge: list[dict[str, Any]] = Field(default_factory=list)
    active_goal: Goal | None = None
    plan: Plan | None = None
    inference_result: dict[str, Any] = Field(default_factory=dict)
    reflection_result: dict[str, Any] = Field(default_factory=dict)
    decision: dict[str, Any] = Field(default_factory=dict)
    response_text: str = ""
    workspace: CognitiveWorkspace = Field(default_factory=CognitiveWorkspace)
    stages_visited: tuple[str, ...] = Field(default_factory=tuple)
    learning_actions: list[dict[str, Any]] = Field(default_factory=list)

    def visit_stage(self, stage_name: str) -> None:
        """Record a visited cognitive stage name.

        Args:
            stage_name: Name of the cognitive stage.

        """
        self.stages_visited = (*self.stages_visited, stage_name)

    @property
    def cognitive_depth(self) -> int:
        """Return total number of cognitive stages visited."""
        return len(self.stages_visited)


CognitiveState.model_rebuild()
