"""Plan and Action — goal-oriented cognitive planning entities.

A Plan is a sequence of Actions generated by the planning subsystem
to achieve a stated goal. Actions are atomic capability invocations.
"""

from __future__ import annotations

from datetime import UTC, datetime
from enum import StrEnum
from typing import Any
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class ActionStatus(StrEnum):
    """Lifecycle status of a planned action."""

    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


class Action(BaseModel, frozen=True):
    """An atomic capability invocation within a plan.

    Attributes:
        id: Unique action identifier.
        capability: Name of the capability to invoke.
        parameters: Parameters to pass to the capability.
        status: Current execution status.
        result: Optional result after execution.
        metadata: Extensible metadata dictionary.

    """

    id: UUID = Field(default_factory=uuid4)
    capability: str
    parameters: dict[str, Any] = Field(default_factory=dict)
    status: ActionStatus = ActionStatus.PENDING
    result: Any | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class Plan(BaseModel):
    """A sequence of actions toward a cognitive goal.

    Attributes:
        id: Unique plan identifier.
        goal: The stated goal this plan is designed to achieve.
        actions: Ordered sequence of actions to execute.
        created_at: UTC timestamp of plan creation.
        metadata: Extensible metadata dictionary.

    """

    id: UUID = Field(default_factory=uuid4)
    goal: str
    actions: list[Action] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    metadata: dict[str, Any] = Field(default_factory=dict)

    @property
    def action_count(self) -> int:
        """Return the number of actions in this plan."""
        return len(self.actions)

    @property
    def is_complete(self) -> bool:
        """Return True if all actions are completed or skipped."""
        terminal = {ActionStatus.COMPLETED, ActionStatus.SKIPPED, ActionStatus.FAILED}
        return all(action.status in terminal for action in self.actions)
