"""Cognitive actions for action sequences generated by the Planner."""

from __future__ import annotations

from theo_core.domain.runtime.entities.plan import Action


def make_action(capability: str, **parameters: object) -> Action:
    """Create a Plan Action item.

    Args:
        capability: Name of the capability or action type.
        **parameters: Parameters for the action.

    Returns:
        An immutable Action instance.

    """
    return Action(
        capability=capability,
        parameters=dict(parameters),
    )
